cache-dir = "tmp.pypoetry"
experimental.new-installer = true
installer.parallel = true
# We don't want poetry to automatically create / manage virtual environment
# (see use devops/docker_build/install_requirements.sh).
#virtualenvs.create = true
virtualenvs.create = false
virtualenvs.in-project = true
