#!/bin/bash -e

# """
# List commits in a fancy full-screen format like:
#
#    * 299ad8e saggese   Improve scripts for tunnelling and handling notebooks             (   4 hours ago) Sat Sep 14 11:28:29 2019  (HEAD -> master, origin/master, origin/HEAD)
#    * f08f8a0 saggese   Fix bug in ssh_tunnel.py and lint                                 (   5 hours ago) Sat Sep 14 10:30:41 2019
#    * 296e6ad saggese   Consolidate all the user info in helpers/user_credentials. Clean up (   6 hours ago) Sat Sep 14 10:17:03 2019
#    * 39b779d saggese   Add script to start jupyter server using the right port (to tunnel through if remote) (   6 hours ago) Sat Sep 14 10:16:49 2019
#    * 3df71ff paul      Lint
#
# One can pass other options, e.g., -n
#
# # Show the last 5 commits:
# > gll -5
# """

source dev_scripts/helpers.sh

# TODO(gp): Make sure that the commit message doesn't overflow.
# TODO(gp): Remove the Git branch pointers.
#GIT_OPTS="--graph --decorate"
GIT_OPTS="--pretty=format:'$GIT_LOG_OPTS'"

CMD="git log --date=local --oneline --date-order $GIT_OPTS $*"
execute $CMD
