#!/bin/bash -e

# """
# Sync client with gup.py and then push local commits.
# """

source helpers.sh

echo "==================== gup.py ===================="
execute "gup.py"

echo
echo "==================== git push ===================="
execute "git push"
