services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 1971
      MYSQL_DATABASE: students_mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1971
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1971"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - mariadb_data:/var/lib/mysql

  flaskapp:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development

volumes:
  mariadb_data:
