# {'build-system': {'build-backend': 'poetry.masonry.api',
#                   'requires': ['poetry>=0.12']},
#  'tool': {'poetry': {'authors': [''],
#                      'dependencies': {'boto3': '*',
#                                       'flaky': '*',
#                                       'fsspec': '*',
#                                       'gluonts': '*',
#                                       'invoke': '*',
#                                       'jupyter': '*',
#                                       'matplotlib': '*',
#                                       'mxnet': '*',
#                                       'networkx': '*',
#                                       'pandas': '^1.1.0',
#                                       'psycopg2': '*',
#                                       'pyarrow': '*',
#                                       'pytest': '^6.0.0',
#                                       'pytest-cov': '*',
#                                       'pytest-instafail': '*',
#                                       'pytest-xdist': '*',
#                                       'python': '^3.7',
#                                       'pywavelets': '*',
#                                       's3fs': '*',
#                                       'seaborn': '*',
#                                       'sklearn': '*',
#                                       'statsmodels': '*'},
#                      'description': '',
#                      'dev-dependencies': {},
#                      'name': 'lem',
#                      'version': '0.1.0'}}}
# 04-20_17:11 DEBUG: _main          : file_name=amp/devops/docker_build/pyproject.toml:
# {'build-system': {'build-backend': 'poetry.masonry.api',
#                   'requires': ['poetry>=0.12']},
#  'tool': {'poetry': {'authors': [''],
#                      'dependencies': {'boto3': '*',
#                                       'bs4': '*',
#                                       'flaky': '*',
#                                       'fsspec': '*',
#                                       'gluonts': '*',
#                                       'invoke': '*',
#                                       'jsonpickle': '*',
#                                       'jupyter': '*',
#                                       'lxml': '*',
#                                       'matplotlib': '*',
#                                       'mxnet': '*',
#                                       'networkx': '*',
#                                       'pandas': '^1.1.0',
#                                       'psycopg2': '*',
#                                       'pyarrow': '*',
#                                       'pytest': '^6.0.0',
#                                       'pytest-cov': '*',
#                                       'pytest-instafail': '*',
#                                       'pytest-xdist': '*',
#                                       'python': '^3.7',
#                                       'pywavelets': '*',
#                                       'requests': '*',
#                                       's3fs': '*',
#                                       'seaborn': '*',
#                                       'sklearn': '*',
#                                       'statsmodels': '*',
#                                       'tqdm': '*'},
#                      'description': '',
#                      'dev-dependencies': {},
#                      'name': 'amp',
#                      'version': '0.1.0'}}}