# Use the official MySQL image from the Docker Hub
FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=projectdb
ENV MYSQL_USER=sumedha1024
ENV MYSQL_PASSWORD=1024

# Copy the SQL script to initialize the database
#COPY init.sql /docker-entrypoint-initdb.d/
