version: '3.8'
services:
  zookeeper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zookeeper
    ports:
      - "2181:2181"

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter
    ports:
      - "8888:8888"
    depends_on:
      - zookeeper
