# Setup
ifdef $(GITHUB_SHA)
IMAGE_RC_SHA:=$(GITHUB_SHA)
else
# GITHUB_SHA not found. Setting up IMAGE_RC_SHA form HEAD.
IMAGE_RC_SHA:=$(shell git rev-parse HEAD)
endif
IB_CONNECT_REPO_BASE_PATH=083233266530.dkr.ecr.us-east-2.amazonaws.com/ib_connect
IB_CONNECT_LATEST_IMAGE=$(IB_CONNECT_REPO_BASE_PATH):latest
IB_CONNECT_PROD_IMAGE=$(IB_CONNECT_REPO_BASE_PATH):prod
IB_CONNECT_RC_IMAGE=$(IB_CONNECT_REPO_BASE_PATH):rc
IB_CONNECT_RC_IMAGE_SHA=$(IB_CONNECT_REPO_BASE_PATH):$(IMAGE_RC_SHA)
ID_CONNECT_RELATED_IMAGES=$(IB_CONNECT_LATEST_IMAGE) $(IB_CONNECT_PROD_IMAGE)

ib_connect.setup_print:
	@echo "IB_CONNECT_REPO_BASE_PATH=$(IB_CONNECT_REPO_BASE_PATH)"
	@echo "IB_CONNECT_LATEST_IMAGE=$(IB_CONNECT_LATEST_IMAGE)"
	@echo "IB_CONNECT_PROD_IMAGE=$(IB_CONNECT_PROD_IMAGE)"
	@echo "IB_CONNECT_RC_IMAGE=$(IB_CONNECT_RC_IMAGE)"
	@echo "IB_CONNECT_RC_IMAGE_SHA=$(IB_CONNECT_RC_IMAGE_SHA)"
	@echo "ID_CONNECT_RELATED_IMAGES=$(ID_CONNECT_RELATED_IMAGES)"
