# Use a small image `alpine` with Python inside.
FROM ubuntu:20.04 AS BUILDER
FROM python:3.10-slim-buster
ENV DEBIAN_FRONTEND noninteractive

# Copy app into image.
# ADD . /code
# Set working dir.

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install gcc python3-dev

RUN apt install -y --no-install-recommends --fix-missing \
    sudo \ 
    curl \
    gnupg \
    git \
    vim \
    jupyter-notebook

ENV INSTALL_DIR=/bitquery
WORKDIR $INSTALL_DIR

# Install requirements.
COPY requirements.txt .
COPY bitquery ./bitquery

RUN pip3 install -r requirements.txt
# Set the default app.

EXPOSE 8888

CMD [ "python", "app.py" ]

ENTRYPOINT (jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='') && \
    /bin/bash

