# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Make template directory
COPY /templates /app/templates

# Upgrade pip
RUN python -m pip install --upgrade pip

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /app
COPY . /app

# Set the environment variable for the database connection URL
ENV DATABASE_URL=postgresql://postgres:postgres@db/db

# Expose ports
EXPOSE 8000
EXPOSE 8001
EXPOSE 5432

# Run the Flask app and connect to PostgreSQL
CMD ["python", "app.py"]
