#!/bin/bash -xe
source amp/dev_scripts/cleanup_scripts/CMTask2669_Rename_initial_replayed_delay.sh
source amp/dev_scripts/cleanup_scripts/CMTask2669_Rename_initial_replayed_dt.sh
source amp/dev_scripts/cleanup_scripts/CMTask2669_Rename_real_time_loop_time_out_in_secs.sh
source amp/dev_scripts/cleanup_scripts/CMTask2669_Rename_sleep_interval_in_secs.sh
source amp/dev_scripts/cleanup_scripts/CMTask2692_Refactor_system_test_case.sh
