# Use an official Python runtime as a base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the application files to the container
COPY sub_patient1.py .

# Install any dependencies required for the application
RUN pip install zmq

# Specify the command to run when the container starts
CMD ["python", "sub_patient1.py"]
