FROM python:3.7-slim-buster

# Install pip.
# RUN pip3 install poetry
    # echo "PIP VERSION="$(pip3 --version)
# apt-get update && \
    #apt-get install postgresql-client -y --no-install-recommends && \
#     echo "PYTHON VERSION="$(python3 --version) && \
#     echo "PIP VERSION="$(pip3 --version) && \

#&& \
#     apt-get install -y --no-install-recommends python3-venv && \
#     apt-get install -y --no-install-recommends python3-pip && \
#     echo "PYTHON VERSION="$(python3 --version) && \
#     echo "PIP VERSION="$(pip3 --version) && \
#     pip3 install poetry && \
#     echo "POETRY VERSION="$(poetry --version) \

WORKDIR /app