#!/bin/bash -e

# """
# Print the status of the clients and of the submodules with
# git status --short
# """

source helpers.sh

if [[ -f .gitmodules ]]; then
  echo "===================== supermodule ====================="
fi;

execute "git status --short $*"

if [[ -f .gitmodules ]]; then
  echo
  echo "===================== submodule ====================="
  execute "git submodule foreach git status --short $*"
fi;
