project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: development
    development:
#        gas_limit: max
#        gas_buffer: 1
#        gas_price: 0
#        max_fee: null
#        priority_fee: null
#        reverting_tx_gas_limit: max
#        default_contract_owner: true
#        cmd_settings: null
        gas_limit: "auto"
        gas_price: "auto"
        persist: true
        reverting_tx_gas_limit: false  # if false, reverting tx's will raise without broadcasting
        host: http://127.0.0.1:7545/
        gas_price: 0
        persist: false
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false
    mainnet:
        host: https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID
    goerli:
        host: https://goerli.infura.io/v3/9153e25e52de479881b1798e0a91318f

compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
    vyper:
        version: null

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs

reports:
    exclude_paths: null
    exclude_contracts: null
    only_include_project: true

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true

autofetch_sources: false
dependencies:
    # - <organization/repo>@<version>
    - OpenZeppelin/openzeppelin-contracts@4.8.0
dev_deployment_artifacts: false
