#import python docker image
FROM python:3.9
#setup work directory
WORKDIR /app
#install needed dependencies
COPY requirements.txt .

RUN pip install jupyter -U && pip install jupyterlab

RUN apt-get update && apt-get install -y libglib2.0-0 libgl1-mesa-glx && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

RUN pip install mariadb

RUN pip install pydub

RUN pip install soundfile
#expose port 8888 on the container
EXPOSE 8888
#run default command
CMD ["jupyter", "lab","--ip=0.0.0.0","--allow-root"]