FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install jupyter -U && pip install jupyterlab

RUN apt-get update && apt-get install -y libglib2.0-0 libgl1-mesa-glx && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

RUN pip install mariadb

EXPOSE 8888

CMD ["jupyter", "lab","--ip=0.0.0.0","--allow-root"]