#!/bin/bash -e

# ```
# Accept our changes in case of a conflict.
# ```

source helpers.sh

FILES=$*
echo "Accepting our version of $FILES"
#cp $* $*.$(timestamp)
exec "git checkout --ours $FILES"
exec "git add $FILES"
