#!/bin/bash -e

# ```
# Accept their changes in case of a conflict.
# ```

source helpers.sh

FILES=$*
echo "Accepting $FILES"
exec "git reset HEAD $FILES"
exec "git checkout --theirs $FILES"
exec "git add $FILES"
