#!/bin/bash -e

# ```
# Accept their changes in case of a conflict.
# ```

source helpers.sh

FILES=$*
echo "Accepting $FILES"
execute "git reset HEAD $FILES"
execute "git checkout --theirs $FILES"
execute "git add $FILES"
