#!/bin/bash -xe

# """
# Like gll / git ll but only referring to your commits.
#
# # Show my last 5 commits.
# > gllmy -5
# """

git log --date=local --oneline --graph --date-order --decorate \
  --pretty=format:'%Creset%Cgreen%h %C(reset)%C(cyan)%<(8)%aN%Creset %Creset%C(bold white) %<(65)%s %C(bold black)(%>(14)%ar) %C(red)%ad %C(yellow)%<(10)%d%C(reset)' \
  --author $(git config user.name) \
  $*
