#!/bin/bash -e

# ```
# Sync client with gup.py and then push.
# ```

source helpers.sh

echo "==================== gup.py ===================="
exec "gup.py"
echo "==================== git push ===================="
exec "git push"
