#!/bin/bash -e

# ```
# Print the status of the clients and of the submodules with
# `git status --short`.
# ```

source helpers.sh

execute "git status --short $*"

echo
echo "===================== submodule ====================="
execute "git submodule foreach git status --short $*"
