#!/bin/bash -e

echo '[stash] saving local changes...'
export UUID=$(uuidgen)
tag="WIP $(date +%Y%m%d-%H%M%S)-$(whoami)-$(hostname) ${UUID}"
cmd="git stash save --quiet $tag"
echo "> $cmd"
eval $cmd

echo
echo '[stash] checking stash head ...'
cmd="git stash list"
echo "> $cmd"
eval $cmd
