#!/bin/bash -e

# ```
# Print the status of the clients and of the submodules with `git status`.
# ```

source helpers.sh

execute "git status $*"

echo "===================== submodule ====================="
execute "git submodule foreach git status $*"
