#!/bin/bash -e

# """
# Search in .py python (not .ipynb) files.
# """

source helpers.sh

parse_jack_cmd_opts "$@"

# --follow: follow the links
#cmd="ack $ACK_OPTS --follow --type=python '$regex' $dir | grep -v ipynb_checkpoints"

cmd="find $dir \( -name '*.py' \) -print0 | xargs -0 ack $ACK_OPTS '$regex'"
execute_with_verbose $cmd
