#!/bin/bash -e

# """
# Search in .py python (not .ipynb) files.
# """

source helpers.sh

parse_jack_cmd_opts "$@"

cmd="ack $ACK_OPTS --type=python '$regex' $dir | grep -v ipynb_checkpoints"
execute $cmd
