#!/bin/bash -e

# """
# Search in .py python (not .ipynb) files.
# """

source helpers.sh

parse_jack_cmd_opts "$@"

# --follow: follow the links
cmd="ack $ACK_OPTS --follow --type=python '$regex' $dir | grep -v ipynb_checkpoints"
execute_with_verbose $cmd
