#!/bin/bash -e

# """
# Search in txt and md files.
# """

source helpers.sh

parse_jack_cmd_opts "$@"

cmd="find $dir \( -name '*.txt' -o -name '*.md' \) -print0 | xargs -0 ack $ACK_OPTS '$regex'"
execute_with_verbose $cmd
