# -*- coding: utf-8 -*-
"""Project DATA605.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IgGdVrfE2swxNS_P6EiNNEoQEXewIlF
"""

!pip install pyspark

from pyspark.sql import SparkSession
from pyspark.streaming import StreamingContext

# Initialize SparkSession
spark = SparkSession.builder \
    .appName("Join Static Datasets") \
    .getOrCreate()

# Read the static datasets
countries_df = spark.read.csv('/content/drive/MyDrive/Countries.csv', header=True, inferSchema=True)
reviews_df = spark.read.csv('/content/drive/MyDrive/ba_reviews.csv', header=True, inferSchema=True)

# Perform the join
joined_df = reviews_df.join(countries_df, reviews_df["place"] == countries_df["Country"], "inner")

# Show the result or perform further operations
joined_df.show()