ALTER TABLE public.ccxt_bid_ask_futures_resampled_1min
    DROP COLUMN bid_size,
    DROP COLUMN bid_price,
    DROP COLUMN ask_size,
    DROP COLUMN ask_price,
    ADD COLUMN ask_price_close numeric,
    ADD COLUMN ask_price_high numeric,
    ADD COLUMN ask_price_low numeric,
    ADD COLUMN ask_price_mean numeric,
    ADD COLUMN ask_price_open numeric,
    ADD COLUMN ask_size_close numeric,
    ADD COLUMN ask_size_max numeric,
    ADD COLUMN ask_size_mean numeric,
    ADD COLUMN ask_size_min numeric,
    ADD COLUMN ask_size_open numeric,
    ADD COLUMN bid_price_close numeric,
    ADD COLUMN bid_price_high numeric,
    ADD COLUMN bid_price_low numeric,
    ADD COLUMN bid_price_mean numeric,
    ADD COLUMN bid_price_open numeric,
    ADD COLUMN bid_size_close numeric,
    ADD COLUMN bid_size_max numeric,
    ADD COLUMN bid_size_mean numeric,
    ADD COLUMN bid_size_min numeric,
    ADD COLUMN bid_size_open numeric,
    ALTER COLUMN knowledge_timestamp SET DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS ccxt_bid_ask_futures_resampled_1min_timestamp_index
ON public.ccxt_bid_ask_futures_resampled_1min(timestamp);

ALTER TABLE public.ccxt_bid_ask_spot_resampled_1min
    DROP COLUMN bid_size,
    DROP COLUMN bid_price,
    DROP COLUMN ask_size,
    DROP COLUMN ask_price,
    ADD COLUMN ask_price_close numeric,
    ADD COLUMN ask_price_high numeric,
    ADD COLUMN ask_price_low numeric,
    ADD COLUMN ask_price_mean numeric,
    ADD COLUMN ask_price_open numeric,
    ADD COLUMN ask_size_close numeric,
    ADD COLUMN ask_size_max numeric,
    ADD COLUMN ask_size_mean numeric,
    ADD COLUMN ask_size_min numeric,
    ADD COLUMN ask_size_open numeric,
    ADD COLUMN bid_price_close numeric,
    ADD COLUMN bid_price_high numeric,
    ADD COLUMN bid_price_low numeric,
    ADD COLUMN bid_price_mean numeric,
    ADD COLUMN bid_price_open numeric,
    ADD COLUMN bid_size_close numeric,
    ADD COLUMN bid_size_max numeric,
    ADD COLUMN bid_size_mean numeric,
    ADD COLUMN bid_size_min numeric,
    ADD COLUMN bid_size_open numeric,
    ALTER COLUMN knowledge_timestamp SET DEFAULT CURRENT_TIMESTAMP;