# Setup
ifdef $(GITHUB_SHA)
IMAGE_RC_SHA:=$(GITHUB_SHA)
else
# GITHUB_SHA not found. Setting up IMAGE_RC_SHA form HEAD.
IMAGE_RC_SHA:=$(shell git rev-parse HEAD)
endif
IB_EXTRACT_REPO_BASE_PATH=083233266530.dkr.ecr.us-east-2.amazonaws.com/ib_extract
IB_EXTRACT_DEV_IMAGE=$(IB_EXTRACT_REPO_BASE_PATH):dev
IB_EXTRACT_PROD_IMAGE=$(IB_EXTRACT_REPO_BASE_PATH):prod
IB_EXTRACT_RC_IMAGE=$(IB_EXTRACT_REPO_BASE_PATH):rc
IB_EXTRACT_RC_IMAGE_SHA=$(IB_EXTRACT_REPO_BASE_PATH):$(IMAGE_RC_SHA)
ID_EXTRACT_RELATED_IMAGES=$(IB_EXTRACT_DEV_IMAGE) $(IB_EXTRACT_PROD_IMAGE)

ib_extract.setup_print:
	@echo "IB_EXTRACT_REPO_BASE_PATH=$(IB_EXTRACT_REPO_BASE_PATH)"
	@echo "IB_EXTRACT_DEV_IMAGE=$(IB_EXTRACT_DEV_IMAGE)"
	@echo "IB_EXTRACT_PROD_IMAGE=$(IB_EXTRACT_PROD_IMAGE)"
	@echo "IB_EXTRACT_RC_IMAGE=$(IB_EXTRACT_RC_IMAGE)"
	@echo "IB_EXTRACT_RC_IMAGE_SHA=$(IB_EXTRACT_RC_IMAGE_SHA)"
	@echo "ID_EXTRACT_RELATED_IMAGES=$(ID_EXTRACT_RELATED_IMAGES)"
