version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis

  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
