version: "3.4"
networks:
  docker_network:

services:
  jobmanager:
    build: .
    image: pyflink:1.18.1
    container_name: jobmanager
    volumes:
      - .:/opt/docker
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - docker_network        

  taskmanager:
    image: pyflink:1.18.1
    volumes:
      - .:/opt/docker
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    networks:
      - docker_network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - docker_network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - docker_network
    depends_on:
      - zookeeper
    
  generator:
    build: generator
    image: generator:1.0
    container_name: generator
    depends_on:
      - kafka
    networks:
      - docker_network

  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - docker_network

  kibana:
    image: kibana:7.8.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - docker_network
