FROM flink:1.18.1
ARG FLINK_VERSION=1.18.1

# Install python3 and pip3
RUN apt-get update -y && \
apt-get install -y python3 python3-pip python3-dev && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install PyFlink
RUN pip3 install apache-flink==${FLINK_VERSION}

# Install Kafka
RUN pip3 install kafka-python

# Download connector libraries
RUN wget -P /opt/flink/lib https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.1.0-1.18/flink-sql-connector-kafka-3.1.0-1.18.jar
RUN wget -P /opt/flink/lib https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-elasticsearch7/3.0.1-1.17/flink-sql-connector-elasticsearch7-3.0.1-1.17.jar

RUN echo "taskmanager.memory.jvm-metaspace.size: 512m" >> /opt/flink/conf/flink-conf.yaml;

# Set Work Directory
WORKDIR /opt/flink

# Command if you want to run the job automatically when container starts
#CMD ["/opt/flink/bin/flink", "run", "-py", "/opt/docker/kafka_flink_integration.py"]

