version: '3.8'

services:
  neo4j:
    container_name: neo4j-server
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    networks:
      - graph-net
 
  spark:
    build: .
    ports:
      - "8080:8888"
      - "4041:4040"
    networks:
      - graph-net


networks:
  graph-net:
